config/routes.rb
Rails.application.routes.draw do
  resources :sections
  resources :assessments do
    get :practise_data
    post :save_answer
    get :show_result
    post :save_practise_answer
  end
  resources :courses do
    get :course_content
    resources :sections do
      collection do
        get :section_info
      end
    end
  end

end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :sections
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/assessments_controller.rb
class AssessmentsController < ApplicationController
  def show
    render json: {"id":"1",
      "questions":[
      {"question":"Explain how you can define a Inclusive range array in CoffeeScript?",
       "answers":{"1":"This range is always defined by (..)","2":"This range is always defined by (...)", "3":"none of these", "4":"1 and 2 both"}
      }]
      }
  end

  def practise_data
    render json: {"id":"1",
      "questions":[
        {"question":"Which countries are in asia continent ?",
         "answers":{"1":"US", "2":"UK", "3":"Australia", "4":"India"}
        }
      ]
    }
  end

  def quiz_correct_answer_data
    render json: {"id":"1",
      "answers":[
      {"question":"First questions",
       "correct_answers":{"1":"correct","2":"incorrect"}
      }]
      }
  end

  def save_answer
    respond_to do |format|
      format.json do
        render json: { status: true, selected_answer: params[:selected_answer],
                       correct_answer: '1' }
      end
    end
  end

  def save_practise_answer
    respond_to do |format|
      format.json do
        render json: { status: true, selected_answer: params[:selected_answer],
                       correct_answer: '4' }
      end
    end
  end

  def show_result
    render nothing: true
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def course_content
     render json: {
        "course_id":1,
        "course_name":"Test course",
        "chapters":[{
          "id":47,
          "parent_id":0,
          "name":"Chapter 1",
          "version_id":8,
          "created_at":"2015-09-23T06:55:03.991Z",
          "updated_at":"2015-09-23T06:55:03.991Z",
          "course_order":0,
          "chapter_order":7340032,
          "content":false,
          "sections":[{
            "id":74,
            "section_type":"text",
            "parent_id":47,
            "name":"Document: test",
            "version_id":8,
            "created_at":"2015-09-29T07:36:44.724Z",
            "updated_at":"2015-09-29T07:36:44.724Z",
            "course_order":4194304,
            "chapter_order":0,
            "content":true
          }, {
            "id":76,
            "section_type":"assignment",
            "parent_id":47,
            "name":"Assessment: Test 1",
            "version_id":8,
            "created_at":"2015-09-29T08:42:52.736Z",
            "updated_at":"2015-09-29T08:42:52.736Z",
            "course_order":4194304,
            "chapter_order":4194304,
            "content":true }, {
            "id":79,
            "section_type":"practice_test",
            "parent_id":47,
            "name":"test",
            "version_id":8,
            "created_at":"2015-09-29T08:49:48.480Z",
            "updated_at":"2015-09-29T08:49:48.480Z",
            "course_order":4194304,
            "chapter_order":6291456,
            "content":false
          }]},
          {
          "id":47,
          "parent_id":0,
          "name":"Chapter 2",
          "version_id":8,
          "created_at":"2015-09-23T06:55:03.991Z",
          "updated_at":"2015-09-23T06:55:03.991Z",
          "course_order":0,
          "chapter_order":7340032,
          "content":false,
          "sections":[{
            "id":74,
            "section_type":"text",
            "parent_id":47,
            "name":"Document: test",
            "version_id":8,
            "created_at":"2015-09-29T07:36:44.724Z",
            "updated_at":"2015-09-29T07:36:44.724Z",
            "course_order":4194304,
            "chapter_order":0,
            "content":true
          }, {
            "id":76,
            "section_type":"assignment",
            "parent_id":47,
            "name":"Assessment: Test 2",
            "version_id":8,
            "created_at":"2015-09-29T08:42:52.736Z",
            "updated_at":"2015-09-29T08:42:52.736Z",
            "course_order":4194304,
            "chapter_order":4194304,
            "content":true
          }, {
            "id":79,
            "section_type":"practice_test",
            "parent_id":47,
            "name":"test",
            "version_id":8,
            "created_at":"2015-09-29T08:49:48.480Z",
            "updated_at":"2015-09-29T08:49:48.480Z",
            "course_order":4194304,
            "chapter_order":6291456,
            "content":false
          }]
        }
      ]}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:title, :content)
    end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def show
    render json: {"details": [{"text":"First chapter", "id": params[:id],
      "author": "kalashri and minakshi" ,
      "topic": "coffeeScript with Backbone.js",
      "details": "Backbone is suitable for projects of just about any size, ranging from the most complex browser-based applications to quite humble little features. In this chapter we will use Backbone and CoffeeScript to build an example of the latter: a user feedback widget that will run right here in the page. Creating it will take us on a speedy tour through Backbone's components: Model, View, Collection, and Router. When we're done, I hope you will use the widget we've built to let me know how you liked the experience."
      }]}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title></title>
  <meta name="description" content="">
  <meta name="author" content="">
  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
  <div class='wrapper' id = "main-container">
  </div>
</body>
</html>
<script type="text/javascript">
  $(function() {
    // BackboneTest is the app name
    window.router = new CourseTaker.Routers.Courses();
    Backbone.history.start();
  });
</script>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @course.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @course.content %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CourseTaking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>